// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=./mocks/mocks_uc.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/ArtemS18/ShortURL-API/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockSlugUseCase is a mock of SlugUseCase interface.
type MockSlugUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSlugUseCaseMockRecorder
	isgomock struct{}
}

// MockSlugUseCaseMockRecorder is the mock recorder for MockSlugUseCase.
type MockSlugUseCaseMockRecorder struct {
	mock *MockSlugUseCase
}

// NewMockSlugUseCase creates a new mock instance.
func NewMockSlugUseCase(ctrl *gomock.Controller) *MockSlugUseCase {
	mock := &MockSlugUseCase{ctrl: ctrl}
	mock.recorder = &MockSlugUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlugUseCase) EXPECT() *MockSlugUseCaseMockRecorder {
	return m.recorder
}

// CreateSlug mocks base method.
func (m *MockSlugUseCase) CreateSlug(ctx context.Context, e *dto.CreateSlugRequest) (*dto.CreateSlugResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSlug", ctx, e)
	ret0, _ := ret[0].(*dto.CreateSlugResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSlug indicates an expected call of CreateSlug.
func (mr *MockSlugUseCaseMockRecorder) CreateSlug(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSlug", reflect.TypeOf((*MockSlugUseCase)(nil).CreateSlug), ctx, e)
}

// GetURL mocks base method.
func (m *MockSlugUseCase) GetURL(ctx context.Context, slug *dto.GetURLRequest) (*dto.GetURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, slug)
	ret0, _ := ret[0].(*dto.GetURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockSlugUseCaseMockRecorder) GetURL(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockSlugUseCase)(nil).GetURL), ctx, slug)
}
