// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=./mocks/mocks_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/ArtemS18/ShortURL-API/internal/entity"
	dto "github.com/ArtemS18/ShortURL-API/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockSlugGenerator is a mock of SlugGenerator interface.
type MockSlugGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSlugGeneratorMockRecorder
	isgomock struct{}
}

// MockSlugGeneratorMockRecorder is the mock recorder for MockSlugGenerator.
type MockSlugGeneratorMockRecorder struct {
	mock *MockSlugGenerator
}

// NewMockSlugGenerator creates a new mock instance.
func NewMockSlugGenerator(ctrl *gomock.Controller) *MockSlugGenerator {
	mock := &MockSlugGenerator{ctrl: ctrl}
	mock.recorder = &MockSlugGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlugGenerator) EXPECT() *MockSlugGeneratorMockRecorder {
	return m.recorder
}

// GenerateSlug mocks base method.
func (m *MockSlugGenerator) GenerateSlug(url *entity.URL) (*dto.CreateSlugDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSlug", url)
	ret0, _ := ret[0].(*dto.CreateSlugDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSlug indicates an expected call of GenerateSlug.
func (mr *MockSlugGeneratorMockRecorder) GenerateSlug(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSlug", reflect.TypeOf((*MockSlugGenerator)(nil).GenerateSlug), url)
}

// MockSlugRepository is a mock of SlugRepository interface.
type MockSlugRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSlugRepositoryMockRecorder
	isgomock struct{}
}

// MockSlugRepositoryMockRecorder is the mock recorder for MockSlugRepository.
type MockSlugRepositoryMockRecorder struct {
	mock *MockSlugRepository
}

// NewMockSlugRepository creates a new mock instance.
func NewMockSlugRepository(ctrl *gomock.Controller) *MockSlugRepository {
	mock := &MockSlugRepository{ctrl: ctrl}
	mock.recorder = &MockSlugRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlugRepository) EXPECT() *MockSlugRepositoryMockRecorder {
	return m.recorder
}

// CreateSlug mocks base method.
func (m *MockSlugRepository) CreateSlug(ctx context.Context, e *dto.CreateSlugDB) (*dto.CreateSlugResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSlug", ctx, e)
	ret0, _ := ret[0].(*dto.CreateSlugResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSlug indicates an expected call of CreateSlug.
func (mr *MockSlugRepositoryMockRecorder) CreateSlug(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSlug", reflect.TypeOf((*MockSlugRepository)(nil).CreateSlug), ctx, e)
}

// GetURL mocks base method.
func (m *MockSlugRepository) GetURL(ctx context.Context, slug *entity.Slug) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, slug)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockSlugRepositoryMockRecorder) GetURL(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockSlugRepository)(nil).GetURL), ctx, slug)
}
