// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/slugs": {
            "post": {
                "description": "Возвращает короткую ссылку для заданного URL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slug"
                ],
                "summary": "Создание короткой ссылки",
                "parameters": [
                    {
                        "description": "URL для сокращения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ArtemS18_ShortURL-API_internal_usecase_dto.CreateSlugRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful creation, returns the created slug",
                        "schema": {
                            "$ref": "#/definitions/github_com_ArtemS18_ShortURL-API_internal_usecase_dto.CreateSlugResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ArtemS18_ShortURL-API_internal_delivery_restapi_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ArtemS18_ShortURL-API_internal_delivery_restapi_utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{slug}": {
            "get": {
                "description": "Возвращает оригинальный URL для заданной короткой ссылки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slug"
                ],
                "summary": "Получение URL по короткой ссылке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Slug",
                        "name": "{slug}",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful retrieval, returns the original URL",
                        "schema": {
                            "$ref": "#/definitions/github_com_ArtemS18_ShortURL-API_internal_usecase_dto.GetURLResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_ArtemS18_ShortURL-API_internal_delivery_restapi_utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_ArtemS18_ShortURL-API_internal_delivery_restapi_utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ArtemS18_ShortURL-API_internal_delivery_restapi_utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                }
            }
        },
        "github_com_ArtemS18_ShortURL-API_internal_usecase_dto.CreateSlugRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_ArtemS18_ShortURL-API_internal_usecase_dto.CreateSlugResponse": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string"
                }
            }
        },
        "github_com_ArtemS18_ShortURL-API_internal_usecase_dto.GetURLResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ShortURL API",
	Description:      "Created by Artemii in 2026",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
